# Generated by Django 2.2.7 on 2019-11-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_register_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
