# Generated by Django 2.2.7 on 2019-11-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20191110_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
