# Generated by Django 2.2.7 on 2019-11-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20191110_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='image_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
