# Generated by Django 2.2.7 on 2019-11-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_register_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='ph_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
