# Generated by Django 2.2.7 on 2019-11-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_auto_20191116_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='channel',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
