# Generated by Django 2.2.7 on 2019-11-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_auto_20191116_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='channel',
            field=models.CharField(max_length=100),
        ),
    ]
