# Generated by Django 2.2.7 on 2019-11-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_auto_20191116_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='channels',
            old_name='user',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='channels',
            name='channel',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
