# Generated by Django 2.2.7 on 2019-11-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_auto_20191121_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='otp',
            field=models.CharField(default=None, max_length=1, null=True),
        ),
    ]
