# Generated by Django 2.2.7 on 2019-11-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0016_channels_motto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
