# Generated by Django 2.2.7 on 2019-11-23 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0017_auto_20191123_1842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
