# Generated by Django 2.2.7 on 2019-12-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0020_auto_20191205_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.CharField(default='06:02:22', max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='time',
            field=models.CharField(default='06:02:22', max_length=100),
        ),
    ]
