# Generated by Django 2.2.7 on 2019-12-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0021_auto_20191205_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.CharField(default='16/12/2019', max_length=100),
        ),
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.CharField(default='10:07:32', max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='date',
            field=models.CharField(default='16/12/2019', max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='time',
            field=models.CharField(default='10:07:32', max_length=100),
        ),
    ]
