# Generated by Django 2.2.7 on 2020-01-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0024_auto_20200116_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.CharField(default='10:05:50', max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='time',
            field=models.CharField(default='10:05:50', max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='channel',
            field=models.CharField(max_length=100),
        ),
    ]
